// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewtbkgmcrqlveqaibwvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3dGJrZ21jcnFsdmVxYWlid3ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzY2ODIsImV4cCI6MjA2NTc1MjY4Mn0.vp8PvMinIHPJ4K6n4PaY27b7Jl6l132CQwKwD99h5EU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
